version: "3"
services:
    php:
        build:
          context: ./
          dockerfile: ./Dockerfile
        volumes:
            - ./app:/app
        restart: unless-stopped

    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./app:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment: 
            - DB_DATABASE=database
            - DB_USERNAME=dbuser
            - DB_PASSWORD=dbpass
        restart: unless-stopped

volumes:
  mysql-data: